name: lms
description: A Flutter project for trading education landing page

publish_to: 'none' # Remove this line if publishing to pub.dev

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.5
  flutter_svg: ^2.0.7
  google_fonts: ^4.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true

  assets:
  # Define image asset directories here if used
  # - assets/images/

